### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by Shu-HowTing** [michuanhaohao/keras_reid#12]
罗博，你好！
看了你写的《**基于深度学习的行人重识别研究综述**》过来的！写的很赞！
阅读了`MLMS losss`部分的代码，有一个疑问，即每个batch大小为`PN*SN`,每次PN个不同的ID，每个ID取SN个样本，最后算损失的时候，我没理解错的话，只得到一个max和一个min，这样是否优点浪费？能否每个ID只跟自己组内算远近，最后每个batch得到PN个max和min呢？

**Comment by michuanhaohao** [comment]
@Shu-HowTing 可以的，这个就是trihard loss，而且我现在更推荐trihard loss，这个更加鲁棒一点

**Comment by michuanhaohao** [comment]
@Shu-HowTing trihard loss应该是PN*SN个max和min
