### ISSUE TITLE
您好, 有个训练问题想问一下

### ISSUE THREAD

**Issue by sgybupt** [michuanhaohao/keras_reid#14]
您好, 我最近在测试这个算法. 
- 我的数据集大约是1800个Id, 每个Id有6~30+的图, 所以我选择的PN是6.  
- 网络结构是Resnet50+Flatten(2048)+FC1800(for cls),  
- 对图片的预处理是水平翻转, 因为还没有跑出一个稳定的效果, 就没有增加normalization
### 出现的问题
- 若将2048的向量作为这张图的feature输出, 我发现在模型训练初期, feature会在100个batch左右变成0, 往后的训练也变成0
- classification的loss从训练开始到很长一段时间都稳定在8左右, triHard_loss在0.6左右(Alpha值) 
- 如果只使用分类网络, 那么分类loss也只是稳定在8左右, 并且model.predict出来的结果是同一个Id 
- 使用Resnet50的预训练模型, 以及您提供的初始化模型 也都类似以上的结果. 
从数据集的角度上来说应该不是问题关键, 因为在我用cv2在训练时显示了输入网络的图片
谢谢作者, 希望讨论

**Comment by sgybupt** [comment]
![image](https://user-images.githubusercontent.com/46191542/53958670-9ff47a80-411c-11e9-9ce3-c94fa36979bc.png)  
大概就会出现这种情况, 并且根据triHard_Loss的计算公式, 第二个featureloss应当有几率小于0.6, 但是在大量迭代中, 始终大于0.6  
分类网络也似乎不起作用, acc绝大部分情况下都是0

**Comment by michuanhaohao** [comment]
网络崩溃是triplet loss训练中很常见的现象，跟数据集、学习率等等很多因素都有关，本质原因就是初始化的点不好，MSML非常不鲁棒，现在有很多更加鲁邦的metric learning方法，这里推荐尝试一下别的方法
