### ISSUE TITLE
get_triplet_data

### ISSUE THREAD

**Issue by RexKing6** [michuanhaohao/keras_reid#5]
您好，我在看了您关于triplet loss和TriHard loss的keras代码复现，其中负责取triplet loss的batch函数：from load_img_data import get_triplet_data, get_triplet_hard_data，我没有找到相关的库包括注释，向您请教一下，如果打扰了，十分抱歉！

**Comment by ahangchen** [comment]
+1

**Comment by michuanhaohao** [comment]
data provider部分是用旷视内部的框架和库实现的，所以我把相关部分删除了，可能需要大家自己根据程序注释重写一下，写起来不是很难的。

日后有空了我会自己重写push一下，谢谢
